spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetoplay
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    defer-datasource-initialization: false